const types = {
  ATTACH_STAR: 'ATTACH_STAR',
  DELETE: 'DELETE',
  DELETE_COMMENT: 'DELETE_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  EDIT_PAGE: 'EDIT_PAGE',
  EDIT_REWARD_COMMENT: 'EDIT_REWARD_COMMENT',
  EDIT_TITLE: 'EDIT_TITLE',
  LIKE: 'LIKE',
  LIKE_COMMENT: 'LIKE_COMMENT',
  LOAD: 'LOAD',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  LOAD_MORE: 'LOAD_MORE',
  LOAD_MORE_COMMENTS: 'LOAD_MORE_COMMENTS',
  LOAD_MORE_REPLIES: 'LOAD_MORE_REPLIES',
  LOAD_PAGE: 'LOAD_PAGE',
  RESET_PAGE: 'RESET_PAGE',
  UPLOAD: 'UPLOAD',
  UPLOAD_COMMENT: 'UPLOAD_COMMENT',
  UPLOAD_REPLY: 'UPLOAD_REPLY'
};

for (let key in types) {
  types[key] = `${types[key]}_LINK`;
}

export default types;
