const types = {
  CHAT_SUBJECT_CHANGE: 'CHAT_SUBJECT_CHANGE',
  CHECK_VERSION: 'CHECK_VERSION',
  CLEAR: 'CLEAR',
  CLEAR_REWARDS: 'CLEAR_REWARDS',
  INCREASE_NUM_NEW_NOTIS: 'INCREASE_NUM_NEW_NOTIS',
  INCREASE_NUM_NEW_POSTS: 'INCREASE_NUM_NEW_POSTS',
  LOAD: 'LOAD',
  LOAD_MORE: 'LOAD_MORE',
  LOAD_MORE_REWARDS: 'LOAD_MORE_REWARDS',
  RESET_NUM_NEW_POSTS: 'RESET_NUM_NEW_POSTS'
};

for (let key in types) {
  types[key] = `${types[key]}_NOTI`;
}

export default types;
