const types = {
  CHANGE_XP: 'CHANGE_XP',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  CLOSE_SIGNIN_MODAL: 'CLOSE_SIGNIN_MODAL',
  EDIT_BIO: 'EDIT_BIO',
  EDIT_PROFILE_PICTURE: 'EDIT_PROFILE_PICTURE',
  INIT_SESSION: 'INIT_SESSION',
  LOAD_USERS: 'LOAD_USERS',
  LOAD_MORE_USERS: 'LOAD_MORE_USERS',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  NOT_EXIST: 'NOT_EXIST',
  OPEN_SIGNIN_MODAL: 'OPEN_SIGNIN_MODAL',
  SEARCH: 'SEARCH',
  SHOW_PROFILE: 'SHOW_PROFILE',
  SIGNUP: 'SIGNUP'
}

for (let key in types) {
  types[key] = `${types[key]}_USER`
}

export default types
