const types = {
  ADD_TAGS: 'ADD_TAGS',
  CHANGE_BY_USER_STATUS: 'CHANGE_BY_USER_STATUS',
  CLOSE_MODAL: 'CLOSE_MODAL',
  DELETE: 'DELETE',
  EDIT_TITLE: 'EDIT_TITLE',
  EMPTY_CURRENT_VIDEO_SLOT: 'EMPTY_CURRENT_VIDEO_SLOT',
  FILL_CURRENT_VIDEO_SLOT: 'FILL_CURRENT_VIDEO_SLOT',
  LIKE: 'LIKE',
  LOAD: 'LOAD',
  LOAD_PAGE: 'LOAD_PAGE',
  LOAD_TAGS: 'LOAD_TAGS',
  LOAD_MORE_REPLIES: 'LOAD_MORE_REPLIES',
  LOAD_MORE_DISCUSSION_COMMENTS: 'LOAD_MORE_DISCUSSION_COMMENTS',
  LOAD_MORE_DISCUSSION_REPLIES: 'LOAD_MORE_DISCUSSION_REPLIES',
  OPEN_MODAL: 'OPEN_MODAL',
  RESET: 'RESET',
  SET_DIFFICULTY: 'SET_DIFFICULTY',
  SET_DISCUSSION_DIFFICULTY: 'SET_DISCUSSION_DIFFICULTY',
  UPLOAD: 'UPLOAD',
  UPLOAD_COMMENT: 'UPLOAD_COMMENT',
  UPLOAD_REPLY: 'UPLOAD_REPLY',
  EDIT_THUMBS: 'EDIT_THUMBS'
};

for (let key in types) {
  types[key] = `${types[key]}_VIDEO`;
}

export default types;
