const types = {
  CHANGE_BY_USER_STATUS: 'CHANGE_BY_USER_STATUS',
  CHANGE_PINNED_PLAYLISTS: 'CHANGE_PINNED_PLAYLISTS',
  CHANGE_PLAYLIST_VIDEOS: 'CHANGE_PLAYLIST_VIDEOS',
  CLEAR: 'CLEAR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CLOSE_PLAYLIST_MODAL: 'CLOSE_PLAYLIST_MODAL',
  CLOSE_REORDER_PINNED_PL_MODAL: 'CLOSE_REORDER_PINNED_PL_MODAL',
  CLOSE_SELECT_PL_TO_PIN_MODAL: 'CLOSE_SELECT_PL_TO_PIN_MODAL',
  DELETE: 'DELETE',
  DELETE_PLAYLIST: 'DELETE_PLAYLIST',
  EDIT_THUMBS: 'EDIT_THUMBS',
  EDIT_TITLE: 'EDIT_TITLE',
  EDIT_PLAYLIST_TITLE: 'EDIT_PLAYLIST_TITLE',
  EMPTY_CURRENT_VIDEO_SLOT: 'EMPTY_CURRENT_VIDEO_SLOT',
  FILL_CURRENT_VIDEO_SLOT: 'FILL_CURRENT_VIDEO_SLOT',
  LIKE: 'LIKE',
  LIKE_PLAYLIST_VIDEO: 'LIKE_PLAYLIST_VIDEO',
  LOAD: 'LOAD',
  LOAD_FEATURED_PLAYLISTS: 'LOAD_PINNED_PLAYLISTS',
  LOAD_MORE_PLAYLISTS: 'LOAD_MORE_PLAYLISTS',
  LOAD_MORE_PL_LIST: 'LOAD_MORE_PL_LIST',
  LOAD_PLAYLISTS: 'LOAD_PLAYLISTS',
  LOAD_PAGE: 'LOAD_PAGE',
  OPEN_MODAL: 'OPEN_MODAL',
  OPEN_PLAYLIST_MODAL: 'OPEN_PLAYLIST_MODAL',
  OPEN_REORDER_PINNED_PL_MODAL: 'OPEN_REORDER_PINNED_PL_MODAL',
  OPEN_SELECT_PL_TO_PIN_MODAL: 'OPEN_SELECT_PL_TO_PIN_MODAL',
  SET_DIFFICULTY: 'SET_DIFFICULTY',
  SET_SEARCHED_PLAYLISTS: 'SET_SEARCHED_PLAYLISTS',
  TURN_OFF_CLICK_SAFE: 'TURN_OFF_CLICK_SAFE',
  TURN_ON_CLICK_SAFE: 'TURN_ON_CLICK_SAFE',
  UPLOAD: 'UPLOAD',
  UPLOAD_PLAYLIST: 'UPLOAD_PLAYLIST'
};

for (let key in types) {
  types[key] = `${types[key]}_VIDEO`;
}

export default types;
